import os
import sys
import re
from dotenv import load_dotenv

from graph.workflow import graph
from utils.logger import info, step, success, error
from utils.tracer import save_trace
from utils.pretty_print import show_agent_output
from utils.save_output import save_agent_output

load_dotenv()

if not os.getenv("OPENAI_API_KEY"):
    raise RuntimeError("OPENAI_API_KEY not found. Check your .env file.")

OUTPUT_DIR = os.path.join(os.getcwd(), "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def extract_and_save_files(code_output: str) -> dict:
    step("Extracting Generated Game Files")

    html = re.search(r"```(?:html|HTML)[^\n]*\n(.*?)```", code_output, re.S)
    css  = re.search(r"```(?:css|CSS)[^\n]*\n(.*?)```",  code_output, re.S)
    js   = re.search(r"```(?:javascript|js|JS)[^\n]*\n(.*?)```", code_output, re.S)

    if not (html and css and js):
        raise RuntimeError("Builder output missing required HTML/CSS/JS blocks.")

    files = {
        "index.html": html.group(1).strip(),
        "style.css":  css.group(1).strip(),
        "game.js":    js.group(1).strip(),
    }

    for fname, content in files.items():
        path = os.path.join(OUTPUT_DIR, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

    success("Game files saved:")
    for fname in files:
        print(f"   → output/{fname}")

    return files


def main():
    info("Agentic Game Builder — CLI Mode")

    try:
        print("\n" + "─"*50)
        idea = input("  Enter your game idea:\n  > ").strip()
        if not idea:
            print("Game idea cannot be empty.")
            sys.exit(1)

        state = {
            "user_input": idea,
            "clarifying_questions": None,
            "clarified_requirements": None,
            "game_plan": None,
            "generated_code": None,
            "validation_result": None,
            "validation_issues": None,
            "iteration": 0,
        }

        step("Running Agent Workflow")
        result = graph.invoke(state)
        info("Workflow complete")

        generated_code = result.get("generated_code")
        if not generated_code:
            raise RuntimeError("No code generated by the builder agent.")

        show_agent_output("builder", generated_code)
        save_agent_output("builder", generated_code)
        extract_and_save_files(generated_code)

        val_result = result.get("validation_result", "unknown")
        val_issues = result.get("validation_issues", [])
        iterations = result.get("iteration", 0)

        print(f"\n  Validation : {val_result}")
        if val_issues:
            print(f"  Issues     : {val_issues}")
        print(f"  Repairs    : {iterations}")

        success("Playable game generated! Open output/index.html in your browser.")

        step("Saving Execution Trace")
        save_trace()
        success("Trace saved to debug/trace.json")

    except KeyboardInterrupt:
        print("\nCancelled.")
        sys.exit(0)
    except Exception as exc:
        error(str(exc))
        sys.exit(1)


if __name__ == "__main__":
    main()
